INSERT INTO turnoatendimento(id,nome) VALUES (1,'ATENDIMENTO SOMENTE PELA MANHA');
INSERT INTO turnoatendimento(id,nome) VALUES (2,'ATENDIMENTO SOMENTE A TARDE');
INSERT INTO turnoatendimento(id,nome) VALUES (3,'ATENDIMENTOS NOS TURNOS DA MANHA E A TARDE');
INSERT INTO turnoatendimento(id,nome) VALUES (4,'ATENDIMENTO NOS TURNOS DA MANHA, TARDE E NOITE');
INSERT INTO turnoatendimento(id,nome) VALUES (5,'ATENDIMENTO COM TURNOS INTERMITENTES');
INSERT INTO turnoatendimento(id,nome) VALUES (6,'ATENDIMENTO CONTINUO DE 24 HORAS/DIA (PLANTAO:INCLUI SABADOS, DOMINGOS E FERIADOS)');
INSERT INTO turnoatendimento(id,nome) VALUES (7,'ATENDIMENTO SOMENTE A NOITE');
